/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Admin;

import Controllers.UsuarioController;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nelson Toneze
 */
public class AtualizarUser extends javax.swing.JFrame {
    UsuarioController usuarioController = new UsuarioController();
    
    /**
     * Creates new form AtualizarUser
     */
    public AtualizarUser() {
        initComponents();
        this.atualizaTabelaUsuario("init");
        setLocationRelativeTo(null);
    }

    public void atualizaTabelaUsuario(String mode) {
        DefaultTableModel model = (DefaultTableModel) tbl_usuarios.getModel();

        var listaUsuarios = usuarioController.listaUsuario();

        model.setRowCount(0);
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        for (int i = 0; i < listaUsuarios.size(); i++) {
            model.addRow(new Object[]{
                listaUsuarios.get(i).getUsuarioId(),
                listaUsuarios.get(i).getUsuarioNome(),
                listaUsuarios.get(i).getUsuarioEmail(),
                listaUsuarios.get(i).getUsuarioLogin(),
                listaUsuarios.get(i).getUsuarioTipo()
            });
        }
        
        listaUsuarios.clear();
    }
    
    public int atualizaUsuario(String usuarioid, String nome, String email, String login, String tipo){
        String senha = "";
        boolean temDadoInvalido = false;
        var listaUsuarios = usuarioController.listaUsuario();

        if ((!tipo.equals("gerente") && !tipo.equals("administrador") && !tipo.equals("funcionario"))) {
            listaUsuarios.clear();
            this.atualizaTabelaUsuario("update");
            return 0;
        } else if (nome.equals("") || email.equals("") || login.equals("")) {
            listaUsuarios.clear();
            this.atualizaTabelaUsuario("update");
            return 1;
        } else {
            String LoginNoBanco = "";
            String EmailNoBanco = "";

            for (int i = 0; i < listaUsuarios.size(); i++) {
                int userId = listaUsuarios.get(i).getUsuarioId();

                if (userId == Integer.parseInt(usuarioid)) {
                    senha = listaUsuarios.get(i).getUsuarioPassword();
                    LoginNoBanco = listaUsuarios.get(i).getUsuarioLogin();
                    EmailNoBanco = listaUsuarios.get(i).getUsuarioEmail();
                    break;
                }
            }
            
            if (!LoginNoBanco.equals(login)) {
                if (usuarioController.verificaSeLoginExiste(login)) {
                    temDadoInvalido = true;
                }
            }

            if (!EmailNoBanco.equals(email)) {
                if (usuarioController.verificaSeEmailExiste(email)) {
                    temDadoInvalido = true;
                }
            }

            if (temDadoInvalido) {
                listaUsuarios.clear();
                this.atualizaTabelaUsuario("update");
                return 2;
            } else {
                
                listaUsuarios.clear();

                usuarioController.alterarUsuario(Integer.parseInt(usuarioid), nome, email, login, tipo.toLowerCase(), senha);
                this.atualizaTabelaUsuario("update");
                return 3;
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_usuarios = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btn_voltar = new javax.swing.JButton();
        btn_atualizar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(228, 255, 255));

        tbl_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Email", "Login", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbl_usuarios);
        if (tbl_usuarios.getColumnModel().getColumnCount() > 0) {
            tbl_usuarios.getColumnModel().getColumn(0).setMinWidth(10);
            tbl_usuarios.getColumnModel().getColumn(0).setPreferredWidth(45);
            tbl_usuarios.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Atualizar Usuários");

        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        btn_atualizar.setBackground(new java.awt.Color(51, 153, 255));
        btn_atualizar.setText("Salvar");
        btn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(btn_atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(jLabel2)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        Admin novaTelaAdmin = new Admin();
        novaTelaAdmin.setLayout(new BorderLayout());
        novaTelaAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizarActionPerformed
        int row = tbl_usuarios.getSelectedRow();
        String id = tbl_usuarios.getValueAt(row, 0).toString();
        String name = tbl_usuarios.getValueAt(row, 1).toString();
        String email = tbl_usuarios.getValueAt(row, 2).toString();
        String username = tbl_usuarios.getValueAt(row, 3).toString();
        String role = tbl_usuarios.getValueAt(row, 4).toString();

        switch(this.atualizaUsuario(id, name, email, username, role)){
            case 0:
                JOptionPane.showMessageDialog(null, "Tipo invalido! Tipos permitidos: administrador, funcionario, gerente", "Tipo invalido", JOptionPane.ERROR_MESSAGE);
                break;

            case 1:
                JOptionPane.showMessageDialog(null, "Alguns campos estão com problemas!", "Preencha todos os campos!", JOptionPane.ERROR_MESSAGE);
                break;

            case 2:
                JOptionPane.showMessageDialog(null, "Este usuário já existe!", "Erro", JOptionPane.ERROR_MESSAGE);
                break;
            case 3:
                JOptionPane.showMessageDialog(null, "Usuario atualizado!", "Sucesso", JOptionPane.PLAIN_MESSAGE);
                break;
        }
    }//GEN-LAST:event_btn_atualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtualizarUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atualizar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbl_usuarios;
    // End of variables declaration//GEN-END:variables
}
