/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Funcionario;

import Controllers.PedidoController;
import Views.Gerente.JPedidosGer;
import java.awt.BorderLayout;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nelson Toneze
 */
public class ListarPedidos extends javax.swing.JFrame {
    private static String usuarioId = "";
    private static String tipoUsuario = "";
    PedidoController pedidoController = new PedidoController();
    /**
     * Creates new form ListarPedido
     */
    public ListarPedidos(String usuarioId, String tipoUsuario) throws ParseException {
        this.usuarioId = usuarioId;
        this.tipoUsuario = tipoUsuario;
        initComponents();
        if(this.tipoUsuario == "funcionario"){
            ItensUI(true);
        } else {
            ItensUI(false);
        }
        atualizaTabelaPedido("init");
        setLocationRelativeTo(null);
    }
    
    public void atualizaTabelaPedido(String mode) throws ParseException {
        DefaultTableModel model = (DefaultTableModel) tbl_pedidos.getModel();
        
        model.setRowCount(0);
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        tbl_pedidos.getColumnModel().getColumn(0).setPreferredWidth(5);
        tbl_pedidos.getColumnModel().getColumn(3).setPreferredWidth(10);
        tbl_pedidos.getColumnModel().getColumn(4).setPreferredWidth(10);
        
        for (int i = 0; i < pedidoController.listaPedidos().size(); i++) {
            
            String dataFechadoEm = "";
            
            if(pedidoController.listaPedidos().get(i).getFechadoEm() != null){
                dataFechadoEm = pedidoController.listaPedidos().get(i).getFechadoEm();
            } else {
                dataFechadoEm = "Ainda aberto";
            }
            model.addRow(new Object[]{
                pedidoController.listaPedidos().get(i).getPedidoId(),
                pedidoController.listaPedidos().get(i).getPedidoNomeCliente(),
                pedidoController.listaPedidos().get(i).getPedidoTelefoneCliente(),
                pedidoController.listaPedidos().get(i).getValorTotal(),
                pedidoController.listaPedidos().get(i).getPedidoStatus(),
                pedidoController.listaPedidos().get(i).getCriadoEm(),
                dataFechadoEm
            });
        }
    }

    public void ItensUI(boolean A){
        btn_fechar_pedido.setEnabled(A); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pedidos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btn_voltar = new javax.swing.JButton();
        btn_fechar_pedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(228, 255, 255));

        tbl_pedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Telefone", "Total", "Status ", "Abertura", "Fechamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_pedidos);
        if (tbl_pedidos.getColumnModel().getColumnCount() > 0) {
            tbl_pedidos.getColumnModel().getColumn(0).setResizable(false);
            tbl_pedidos.getColumnModel().getColumn(1).setResizable(false);
            tbl_pedidos.getColumnModel().getColumn(2).setResizable(false);
            tbl_pedidos.getColumnModel().getColumn(3).setResizable(false);
            tbl_pedidos.getColumnModel().getColumn(4).setResizable(false);
            tbl_pedidos.getColumnModel().getColumn(5).setResizable(false);
            tbl_pedidos.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Listar Pedidos");

        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        btn_fechar_pedido.setText("Fechar Pedido");
        btn_fechar_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fechar_pedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(384, 384, 384))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_fechar_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(368, 368, 368))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_fechar_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        if ("funcionario".equals(tipoUsuario)){
            JPedidosFunc novaTelaFuncionario = new JPedidosFunc(usuarioId);
            novaTelaFuncionario.setLayout(new BorderLayout());
            novaTelaFuncionario.setVisible(true);
            this.dispose();
        }
        else if ("gerente".equals(tipoUsuario)){
            JPedidosGer novaTelaGerente = new JPedidosGer(usuarioId);
            novaTelaGerente.setLayout(new BorderLayout());
            novaTelaGerente.setVisible(true);
            this.dispose();
        }
            
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_fechar_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fechar_pedidoActionPerformed
        int row = tbl_pedidos.getSelectedRow();
        String nomeCliente = String.valueOf(tbl_pedidos.getValueAt(row, 1));
        int id = row + 1;
        if (pedidoController.alteraPedido("fechado", id, nomeCliente)){
            JOptionPane.showMessageDialog(null, "Pedido fechado com sucesso", "Pedido Fechado", JOptionPane.PLAIN_MESSAGE);
        }
        try {
            atualizaTabelaPedido("update");
        } catch (ParseException ex) {
            Logger.getLogger(ListarPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_fechar_pedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ListarPedidos(usuarioId, tipoUsuario).setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(ListarPedidos.class.getName()).log(Level.SEVERE, null, ex);
                }
                }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_fechar_pedido;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_pedidos;
    // End of variables declaration//GEN-END:variables
}
